- values.yaml
generated by [UpdateBot](https://github.com/fabric8io/updatebot)
> Pulling new versions

- requirements.yaml
- values.yaml
also adds comments showing how to add Gitea or GHE git servers
> chore: upgrade jenkins chart

- values.yaml
> remove jenkins-git-credentials

- values.yaml
also add the gitlab config sample
> update to the latest image

- templates/jenkins-x-pod-templates.yaml
so that we can support https://github.com/jenkins-x/jx/issues/718#issuecomment-384591446
> add support for pod templates as a ConfigMap

- Makefile
- requirements.yaml
- templates/jenkins-x-docker-registry.yaml
- templates/jenkins-x-pod-templates.yaml
so that we can more easily configure the registry used by Dev Pods
> fix: add a ConfigMap to store the docker registry host/port

- requirements.yaml
- values.yaml
lets make it simpler to override the docker host path / mount path without having to copy/paste the entire pod template tree
> fix: better fix for PKS to make it easier to override docker host path

- requirements.yaml
as this fails for multi-team install
> fix: remove the pipelines CRD chart

- requirements.yaml
- values.yaml
so that we can use the new path based ingress policy
> fix: upgrade nexus and exposecontroller

- requirements.yaml
- values.yaml
and avoid regression with eager creation of the ConfigMap on jobs
> fix: upgrade exposecontroller

- values.yaml
Added missing clusterroles for gc-activities cron job.
> Added missing clusterroles for gc-activities

- README.md
- Added hyphens on `L10-12` to match `L9`
- Corrected `L45` "you kubernetes cluster" to "your kubernetes cluster"
- Added comma on `L52` for grammar/readability
> Minor readability edits

- requirements.yaml
- values.yaml
Bump Jenkins chart version and add defaults for auth values
> Jenkins custom auth

- values.yaml
Reverts jenkins-x/jenkins-x-platform#4178
> Revert "update jenkinsxio/builder-base to 0.1.12"

- values.yaml
See https://github.com/jenkins-x/jenkins-x-builders/pull/20 .
> Added Maven-Java11 builder

- templates/docker-cfg-secret.yaml
- values.yaml
also add first spike of pod GC job
> fix: role controller roles

- values.yaml
Reverts jenkins-x/jenkins-x-platform#4398
> Revert "the team controller was stuck on a very old version of jx."

- values.yaml
> fix: build controller's git configuration

- values.yaml
Corresponding builder https://github.com/jenkins-x/jenkins-x-builders/pull/141
> Adding Python 3.7 builder pod template

- values.yaml
fixes https://github.com/jenkins-x/jx/issues/2218
> fix: update roles on the gc jobs

- OWNERS
grant jtnord review and approve access to this repo
> chore: Add jtnord to the owners file

- values.yaml
Added configuration for the following Builder Pod image - https://hub.docker.com/r/jenkinsxio/builder-maven-nodejs .
> Added Builder Pod configuration for Maven+Nodejs

- values.yaml
Created Helm configuration for AWS CDK image (https://hub.docker.com/r/jenkinsxio/builder-aws-cdk).
> Added configuration for AWS CDK builder pod

- values.yaml
as the latest image looks broken
> fix: downgrade to an older jenkins image

- values.yaml
enlarge maven heap memory limit
> enlarge maven heap memory limit at jenkins-x/jx issue#3098

- values.yaml
so that build logs are more informative
> fix: lets disable noisy maven download messages

- values.yaml
Resolves https://github.com/jenkins-x/jx/issues/3506
> Add patch permission to controllerbuild

- jenkins-x.yml
> fix: container isn't valid, but it isn't needed anyway

- jenkins-x-platform/templates/jenkins-x-pod-templates.yaml
The idea is support mapping Persistent Volume Claim when you upgrade or install using myvalues.yaml
> Adding support to mapping Persistent Volume Claim

- jenkins-x-platform/values.yaml
Please review carefully to ensure that I have the syntax right here. I have some concerns about the correct use of capitalisation...
> Added Machine Learning builder to platform

- jenkins-x-platform/values.yaml
Signed-off-by: Terry Cox <terry@bootstrap.je>
> feat: Add builder for training Machine Learning projects using CUDA

- jenkins-x-platform/values.yaml
Signed-off-by: Carlos Sanchez <carlos@apache.org>
> feat: maven-graalvm pod template

- jenkins-x-platform/values.yaml
- jenkins-x.yml
Standardise all images to builder-jx
Signed-off-by: warrenbailey <warren@warrenbailey.net>
> fix: standardise build images

- OWNERS
remove @jtnord and @i0n 
add @abayer
> chore: tidy owners

- Makefile
> fix: jx step create pr regex --regex, not jx step create pr --regex

- Makefile
It looks like this build never got properly updated to support tekton as it was still doing it’s own tagging. So every release build caused two releases
> chore: no double tagging

- jenkins-x-platform/values.yaml
Adding required vault permissions to GC previews
Signed-off-by: warrenbailey <warren@warrenbailey.net>
> fix: Add vault permission to GC previews

- jenkins-x-platform/values.yaml
we don't need workflow or team controller any more
> fix: lets disable some old controllers OOTB

- README.md
- Added license section
- Added missing punctuation
> chore(docs): Updated README.md

- README.md
Readme - Fixed the image links and incorrect reference.
> Readme update.  Fix hyperlinks and Sonatype reference.

- OWNERS
- jenkins-x-platform/values.yaml
> fix: gcactivities now needs permissions for ProwJobs

- dependency-matrix/matrix.md
- dependency-matrix/matrix.yaml
- jenkins-x-platform/requirements.yaml
> fix: Revert Nexus from 0.1.19 to 0.1.7 due to login issues

- jenkins-x-platform/values.yaml
fixes https://github.com/jenkins-x/jx/issues/6473
> fix: gcpreviews needs tekton.dev/conditions list permissions

- jenkins-x-platform/requirements.yaml
> fix: Remove workflow controller as unused

- OWNERS
- jenkins-x-platform/requirements.yaml
- jenkins-x-platform/values.yaml
> fix: Update chartmuseum and heapster to versions using apps/v1

- jenkins-x-platform/values.yaml
Adding this builder
https://github.com/jenkins-x/jenkins-x-builders/pull/1348
> feat: Maven-java-14 pod template

- jenkins-x-platform/values.yaml
> chore: Add builder-maven-graalvm-java11 builder

- jenkins-x.yml
> fix: Use modern tekton paths

- jenkins-x-platform/requirements.yaml
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
fixes #7282
> fix: update version of jenkins charts version

- Makefile
- jenkins-x.yml
> fix: Switch to properly mounted secrets

- jenkins-x-platform/requirements.yaml
- jenkins-x-platform/values.yaml
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
fixes #7240
> refactor: remove heapster chart
