- README.md
Minor fix in the `Local development` section
> Typo on git repository name

- values.yaml
This commit is a simple change that switches the displayprovider to use blueocean as a redirect instead of the classic UI. This provides a more up-to-date and streamlined view for viewing pipelines.
It would be nice to configure this - but talking to @rawlingsj and @jstrachan this seemed like a good default. 
In order to run this and see it for yourself - you can edit `~/.jx/cloud-environments/env-gke/myvalues.yaml` to be [this gist](https://gist.github.com/rawlingsj/8cb8929e97053d101fb5f44c4abdf8cc) (shoutout to @rawlingsj for providing this!). Then rerun `jx install` -- this is still a little rough and you might have to address [this issue](https://github.com/jenkins-x/jx/issues/666).
But once done your PR builds should -> blue ocean!
> Default UI to blueocean

- templates/jenkins-x-pod-templates.yaml
since the new change to make the docker socket host/mount paths easier to configure lets apply the same change to the DevPods
> fix: build pods docker socket

- requirements.yaml
- templates/chartmuseum-link-service.yaml
- templates/nexus-link-service.yaml
- values.yaml
lets make it easy to service link to other nexus / chart museum repos
and disable things like monocular and pipelinecontroller
> fix: make jenkins-x-platform more modular and allow service linking

- values.yaml
Issues getting the Jenkins API token
This reverts commit da021dbb7053c28295d037f0356bbfaa3eee80df.
> Revert "feat: update jenkins image to version 0.0.29"

- values.yaml
Hi,
I've fixed another missing permission problem in gc-activities. This one is required by prow.
> Added missing `apps.deployments` apiGroup to gc-activities role

- values.yaml
This is the Pod Template definition that corresponds to the builder-newman image (https://github.com/jenkins-x/jenkins-x-builders/pull/15)
The image version was set to 0.0.1, although no corresponding builder-newman image exists in the jenkinsxio repository yet.
> Add a Newman pod template

- values.yaml
This change should be merged after https://github.com/jenkins-x/jenkins-x-image/pull/41 and should use 
the updated version of jenkinsx image. 
Fixes #4208
> fix: update jnlp-slave to version 3.26-1

- values.yaml
lets add port 8080 to node/js devpods as thats the default for apps via `npm start`
> chore: improve devpod ports

- templates/committer-role.yaml
- templates/owner-role.yaml
- templates/viewer-role.yaml
Especially `jx get applications` doesn't work for a non admin with the previous role definitions
Other than solving that I have tried to add api groups that it seems a reasonable a user might need
to add resources from.
When all api groups have the same permissions I have removed the superfluous one.
> Give users permissions for other api groups than core and jenkins.io

- templates/jenkins-x-pod-templates.yaml
- values.yaml
first commit on getting annotation options in for pod templates to address issue #4513.
Work in progress - Ive got it to work properly and update the jenkins-x-pod-templates config map properly, but I cannot find where this config map gets pushed into the config for jenkins. Missing a piece of the puzzle.
> Added in annotation option in cm for pod templates

- values.yaml
This is the second part of the "delete the helm release when deleting the preview environment" fix, and depends on the jx PR https://github.com/jenkins-x/jx/pull/2668
If the team setting is to use a local tiller, then the gcpreview job will need to have sufficient rights to create/delete resources.
To handle this, I added a new feature in the jx chart: setting a custom service account name. This allows to run a pod with an existing service account, without creating a new one.
This PR setup the gcpreviews with the jenkins service account - which is cluster-admin, so that it get enough rights to run a local tiller, when deleting helm charts used by preview environments
> gcpreviews should run with the jenkins serviceaccount

- templates/committer-role.yaml
- templates/owner-role.yaml
- values.yaml
The service account controller role is running as needs both permissions to change permissisons in
all the teams namespaces, so in practice it needs to be in the ClusterRole. Also it needs all the
permissions it is assigning to others itself.
While at it I give the committer and owner roles pod permissions (most importantly exec).
> fix: Give service account for role controller enough permissions

- values.yaml
fixes https://github.com/jenkins-x/jx/issues/2723
> fix: use a docker image with jx + helm + kubectl for gc previews

- values.yaml
which simplifies the Jenkinsfiles and the changes to them if folks want to use different java versions
> chore: lets use maven as the container name for all java versions

- values.yaml
#8 by @rawlingsj was wrong from the start, but with anonymous access enabled, no one noticed. As of https://github.com/jenkins-x/nexus/pull/26 by @garethjevans, this broke access to Nexus for anyone running Maven-based projects who recently ran `jx upgrade platform`, as noted recently in https://github.com/jenkins-x/jx/issues/2052#issuecomment-458466586.
Fix verified locally by means of `kubectl edit secret jenkins-maven-settings`.
> fix: for ~/.m2/settings.xml the server.id must align with mirror.id

- templates/kaniko-secret.yaml
Workaround until Kubernetes Credentials Provider can deal with a secret without annotations.
> Dummy annotation into kaniko-secret as workaround.

- templates/jenkins-x-pod-templates.yaml
fixes https://github.com/jenkins-x/jx/issues/1998
_For some reason_, Helm cannot find Tiller when the `TILLER_NAMESPACE` environment variable is set to an empty string.
Note to JX devs: I didn't test this!  This was just a "best guess"
> fix: do not set TILLER_NAMESPACE to an empty string

- values.yaml
Fixing: https://github.com/jenkins-x/jx/issues/3297
`jenkins` service account is not created when using serverless jenkins configuration, replacing it by a dedicated service account for gcpreviews jobs.
> Make gcpreviews using it's own service account

- values.yaml
This PR fixes Jenkins Pod template name for Maven-Java11 to use `maven-java11` in order to avoid the same pod name conflict created by Maven pod template.
> fix: duplicate Maven-Java11 pod template name

- values.yaml
Fixing https://github.com/jenkins-x/jx/issues/3430
Follow up of https://github.com/jenkins-x/jenkins-x-platform/pull/5012
There was an indentation issue that I missed during my testing and that prevents the clusterrole to be created.
Sorry for that.
> Fix indentation to create clusterrole for gcpreviews

- templates/jenkins-x-docker-registry.yaml
Removed trailing `-` characters from if-else in helm chart to keep newline characters in the generated yaml.
fixes https://github.com/jenkins-x/jx/issues/3494
> Fix if-else to keep newline character

- jenkins-x-platform/values.yaml
to avoid things breaking if the code does a patch instead of update
> fix: add patch roles to all updates roles

- dependency-matrix/matrix.md
- dependency-matrix/matrix.yaml
- jenkins-x-platform/values.yaml
Update [jenkins-x/jenkins-x-builders](https://github.com/jenkins-x/jenkins-x-builders) from 0.1.564 to 1.2.3
Command run was `jx step create pr chart --name gcr.io/jenkinsxio/builder-maven-nodejs --version 1.2.3 --repo https://github.com/jenkins-x/jenkins-x-platform.git`
> chore(deps): bump jenkins-x/jenkins-x-builders from 0.1.564 to 1.2.3

- dependency-matrix/matrix.md
- dependency-matrix/matrix.yaml
- jenkins-x-platform/values.yaml
Update [jenkins-x/jenkins-x-builders](https://github.com/jenkins-x/jenkins-x-builders) from 1.2.3 to 0.1.564
Command run was `jx step create pr chart --name gcr.io/jenkinsxio/builder-maven-nodejs --version 0.1.564 --repo https://github.com/jenkins-x/jenkins-x-platform.git`
> chore(deps): bump jenkins-x/jenkins-x-builders from 1.2.3 to 0.1.564

- Makefile
- jenkins-x-platform/values.yaml
Fixing issue: https://github.com/jenkins-x/jx/issues/3430
gcpreviews service account was missing some roles in order to cleanup the preview envs.
Not sure this solution is ideal, it will depend on the possibility for preview env to create different kind of resources depending on application specificities.
I don't want to give full admin access to this service account though so I'm happy to have some feedback on that.
> Fix gcpreviews service account roles

- jenkins-x-platform/values.yaml
In order to find the vault service the GC preview jobs needs permission to list and get the ingresses
Signed-off-by: warrenbailey <warren@warrenbailey.net>
> fix: add ingress permission for GC previews

- jenkins-x-platform/values.yaml
> fix: controllerworkflow should use the gcr image, not docker.io

- jenkins-x-platform/values.yaml
Signed-off-by: Daniel Gozalo <dgozalo@cloudbees.com>
Removing the `ConfigMap` permissions from `ControllerBuild` because we are moving the data to the `Dev` `Environment` CRD and this is causing issues.
> feat: remove configmap permissions from ControllerBuild

- jenkins-x-platform/templates/jenkins-x-pod-templates.yaml
- fix: template the args and command of the devpod containers
It currently overrides the default cmd of any container other than the building container.
- fix: use container IsBuilder attribute to place it at the top of the containers list
This fixes the issue when there are sidecar containers (e.g DinD container) and we want to make sure the builder container is at the top of the containers list, so it gets selected when logging into a DevPod.
- fix: fix container cpu and memory limits
The wrong variables were being accessed
> Pod template fixes

- dependency-matrix/matrix.md
- dependency-matrix/matrix.yaml
- jenkins-x-platform/requirements.yaml
0.1.18 is failing with `PostStartHookError: command '/opt/sonatype/nexus/postStart.sh' exited with 1: ERROR: Login to nexus failed. Tried both the default password and the provided password secret file.`.
> fix: Revert nexus chart to 0.1.7

- jenkins-x-platform/values.yaml
When there's a `jx-auth-config` configmap present, we end up needing a
_lot_ more permissions to run `jx step git credentials`. I _think_
this is right, but I may be drastically overshooting, so I want to
make sure @ccojocar in particular reviews this.
fixes https://github.com/jenkins-x/jx/issues/6568
> fix: controllerbuild needs to be able to get git credentials

- jenkins-x-platform/requirements.yaml
- jenkins-x-platform/values.yaml
In order to make this chart work in a cluster without cluster-wide permissions, we need to add the namespace permissions to the namespaced role and add a way to disable Heapster.
> feat: add namespace permissions to namespace scoped role and make heapster conditional

- jenkins-x-platform/values.yaml
Give the `controllerbuild` role extra permissions to match the `clusterrole` ones.
Also give the `controllerrole` role a "namespace admin" rights so it can be deployed on other namespaces and let the `controllerrole` controller work without cluster wide permissions.
> fix: add extra permissions to the controllerbuild and give "namespace admin" to controllerrole

- jenkins-x-platform/requirements.yaml
Change the version of the helm chart for docker-registry to 1.8.3 to remove the usage of deprecated apis. https://github.com/helm/charts/pull/17454/files
> refactor: bump up docker registry chart version

- jenkins-x-platform/templates/committer-role.yaml
- jenkins-x-platform/templates/owner-role.yaml
- jenkins-x-platform/templates/viewer-role.yaml
- jenkins-x-platform/values.yaml
The roles created when provisioning a Jenkins X Cluster are static - it would be useful to allow the administrator to override the rules for each role based on their needs.
> feat: allow the team roles rules to be overridden

- jenkins-x-platform/requirements.yaml
> fix: Upstream chartmuseum can't be upgraded to from our variant
